import type { Brand, Course } from '@/lib/course'

export const yoobee: Brand = {
  id: 'yoobee',
  name: 'Yoobee',
  legalName: 'Yoobee College of Creative Innovation',
  wordmark: { title: 'Yoobee', sub: 'College of Creative Innovation' },
  banner: {
    text: 'February 2027 intakes are free for domestic students.',
    linkLabel: "Sign up, it's free.",
    href: '#intakes',
  },
  nav: [
    { label: 'Courses', href: '/courses', current: true },
    { label: 'Campuses', href: '/campuses' },
    { label: 'About Yoobee', href: '/about' },
    { label: 'Schools', href: '#' },
    { label: 'Contact Us', href: '/contact' },
  ],
  enrolHref: '#intakes',
  phone: '0800 66 55 44',
  footerBlurb:
    'Yoobee College of Creative Innovation. Part of UP Education. Online, and on campus in Auckland, Wellington and Christchurch.',
  footerCols: [
    { h: 'Courses', links: ['All courses', 'Design', 'Animation', 'Film', 'Game development', 'Technology', 'Micro-credentials'] },
    { h: 'Campuses', links: ['Online', 'City Road (Auckland)', 'Bunny Street (Wellington)', 'Colombo Street (Christchurch)'] },
    { h: 'Support', links: ['Student support and wellbeing', 'Fees, refunds and withdrawal', 'How to enrol', 'International students'] },
  ],
  themeColor: '#141414',
}

export const creativeMediaLevel4: Course = {
  id: 'creative-media-l4',
  brand: yoobee,
  deliveredBy: 'Yoobee College of Creative Innovation',
  discipline: 'Creative media',
  disciplineSlug: 'design',
  title: 'New Zealand Certificate in Digital Media and Design (Level 4)',
  slug: 'creative-media-certificate',
  delivery: 'online',
  copy: {
    heroTry: "Sign up, it's free",
    heroTryHref: '#intakes',
    feeSub: 'Free for domestic students, Feb 2027 intakes.',
    promise: 'Try it for two weeks. Not for you? Walk away, nothing owed.',
    likeTitle: 'A Wednesday, from your kitchen table',
    likeVideoLabel: 'Play video: a student-recorded online class, captioned',
    kitTitle: 'Your readiness kit',
    kitStep: 'Step 1 · The day you sign up',
    skillsTitle: "What you'll be able to make, and what it means to a studio lead",
    jobNoun: 'a creative job or further study',
    coach: {
      name: 'Yoobee Career Coach',
      initials: 'YC',
      industry: 'creative media, design, animation and film',
      placeholder: 'Ask anything about the course, the free bit, or where it leads',
      starters: [
        'How is this actually free? What is the catch?',
        'Can I get help with living costs while I study?',
        'Animation, film or design. Which one is me?',
        'I work part time. Can I fit this in?',
      ],
      tryLabel: 'Start a free pre-start course now',
      tryHref: '#intakes',
    },
  },
  hero: {
    h1: 'Make a living off creative media',
    sub: 'Animation, film and design in one online certificate. Learn live with a tutor, build a portfolio across all three, and walk into a junior creative role or a Level 5 diploma.',
    image: '/images/yoobee/hero-home-studio.png',
    imageAlt: 'A student at a kitchen table animating a 2D character on a laptop with a drawing tablet',
  },
  fee: {
    year: 2027,
    amount: 0,
    standardAmount: 4753,
    includes: 'Software licences and an AI Pro subscription included',
    gstInclusive: true,
    freeNote: 'Free for domestic students starting February 2027. Otherwise $4,464.72 tuition plus $102.50 levy and $186 software, $4,753 total.',
  },
  funding: {
    loanApproved: true,
    efts: 0.5,
    weeks: 19,
    fullTime: true,
    applyBy: '2026-12-15',
    applyByLabel: '15 Dec 2026',
    courseRelatedCosts: 1000,
    livingCostsMax: 333,
  },
  outcomes: {
    stat: { label: 'In a creative job or further study within 6 months', value: '84%', cohort: 2025 },
    salary: { start: 52000, threeYear: 68000, source: 'Designers Institute of NZ salary survey', year: 2025 },
    employers: ['Weta Workshop', 'Mukpuddy Animation', 'DDB Aotearoa', 'Trade Me', 'Sky', 'Watermark Creative'],
    employersMore: 40,
    employersYear: 2025,
    story: {
      initials: 'HN',
      text: 'I did the animation pre-start course in the summer while I was still working at the supermarket. By the time the course started I was already ahead, and with the Student Allowance I could drop to one shift a week.',
      course: 'Creative Media L4',
      campus: 'Online',
      year: 2025,
      consent: true,
    },
  },
  quick: {
    nextStart: '8 Feb 2027',
    length: '19 weeks',
    where: 'Online',
    need: '16+, NCEA L2',
    get: 'NZ Cert L4',
  },
  aiPerk: {
    lede: 'Your kit is an AI Pro subscription for the whole course, on us, and it switches on the day you sign up. Pick the one you want to think with and start playing months before class.',
    months: 5,
    options: [
      { id: 'claude', name: 'Claude Pro', vendor: 'Anthropic', blurb: 'Strong at writing, critique and long briefs. Good for scripts and design rationale.', monthly: 35 },
      { id: 'chatgpt', name: 'ChatGPT Plus', vendor: 'OpenAI', blurb: 'Image generation and voice built in. Good for moodboards and quick concept art.', monthly: 35 },
      { id: 'gemini', name: 'Gemini Advanced', vendor: 'Google', blurb: 'Lives inside Docs and Drive. Good for research and organising a portfolio.', monthly: 33 },
    ],
  },
  microCredentials: [
    {
      id: 'taster',
      title: 'Creative Media Taster',
      strand: 'All strands',
      image: '/images/yoobee/mc-taster.png',
      imageAlt: 'A young person on a couch watching a creative tutorial on a laptop with a sketchbook beside them',
      make: 'A 10-second animated logo, a one-shot film and a poster. One evening, three tiny projects.',
      hours: 2,
      credits: 0,
      startsNow: true,
      taster: true,
    },
    {
      id: 'anim-foundations',
      title: 'Frame-by-frame animation',
      strand: 'Animation',
      image: '/images/yoobee/mc-animation.png',
      imageAlt: 'A drawing tablet and laptop showing a hand-drawn 2D walk cycle with onion-skin frames',
      make: 'A looping walk cycle in Adobe Animate, plus the 12 principles you will be quizzed on in week 3.',
      hours: 12,
      credits: 5,
      startsNow: true,
    },
    {
      id: 'shot-types',
      title: 'Storyboarding and shot types',
      strand: 'Film',
      image: '/images/yoobee/mc-film.png',
      imageAlt: 'A hand-drawn six-panel storyboard beside a phone on a tripod filming a kitchen scene',
      make: 'A six-panel storyboard and a 30-second scene shot on your phone, cut in Premiere Pro.',
      hours: 10,
      credits: 5,
      startsNow: true,
    },
    {
      id: 'type-layout',
      title: 'Typography and layout',
      strand: 'Design and web',
      image: '/images/yoobee/mc-design.png',
      imageAlt: 'A laptop showing a poster layout in progress next to printed type specimens',
      make: 'An A3 gig poster and its Instagram version, with a one-page rationale you will reuse in your portfolio.',
      hours: 10,
      credits: 5,
      startsNow: true,
    },
  ],
  like: {
    video: null,
    videoPoster: '/images/yoobee/video-poster.png',
    videoCaption: 'Harriet, 22, records a Wednesday online class from Whanganui. 74 seconds, captioned.',
    text: 'Two live online classes a day, 10am and 1pm, about 15 hours a week with a tutor and your class on camera. The rest is making: around 20 hours a week of your own time on projects, with tutor feedback in the shared channel within a day. You need a laptop or desktop that can run Adobe apps and a webcam. You do not need to live near a campus. A part-time online option runs the same weeks over 38.',
    schedule: 'about 15 hours a week of live online classes plus roughly 20 hours of your own project time; a 38-week part-time option runs the same content online',
  },
  stages: [
    {
      label: 'By week 5',
      voice: {
        text: 'I had a walk cycle looping on my phone lock screen by week three. Everyone in my class was sending each other theirs.',
        name: 'Mercy',
        campus: 'Online',
        surveyed: 'Week 5 NPS survey, 2025',
        consent: true,
      },
      items: [
        {
          can: 'Animate a character frame by frame',
          means: 'Rig and draw a walk cycle in Adobe Animate that obeys timing, spacing and squash and stretch.',
        },
        {
          can: 'Design a character from a brief',
          means: 'Concept sketches to a clean digital turnaround in Photoshop and Illustrator.',
          quote: {
            text: 'A student who can show me timing charts and a clean turnaround has saved me a fortnight of teaching.',
            role: 'Animation Director',
            venue: 'Mukpuddy Animation',
            city: 'Auckland',
            approvedOn: '2026-08-12',
            approvedBy: 'L. Reid, Industry Partnerships',
          },
        },
        {
          can: 'Set type properly',
          means: 'Hierarchy, measure and leading on a real poster, not a template.',
        },
      ],
    },
    {
      label: 'By week 12',
      voice: {
        text: 'We shot a two-minute short with three people in three cities. Our tutor cut it live with us on the call. That was the moment.',
        name: 'Tane',
        campus: 'Online',
        surveyed: 'Week 12 NPS survey, 2025',
        consent: true,
      },
      items: [
        {
          can: 'Plan, shoot and cut a short film',
          means: 'Script, storyboard, camera operation and an edit in Premiere Pro with motion graphics and basic VFX.',
        },
        {
          can: 'Design and build a web page',
          means: 'Wireframe in Adobe XD, build in Webflow, test with real people and fix what they trip on.',
          quote: {
            text: 'If they arrive knowing a design process end to end, I can put them on client work in month one.',
            role: 'Creative Director',
            venue: 'Watermark Creative',
            city: 'Christchurch',
            approvedOn: '2026-07-30',
            approvedBy: 'L. Reid, Industry Partnerships',
          },
        },
        {
          can: 'Use AI like a pro, not a shortcut',
          means: 'Moodboards, first drafts and critique with your AI subscription, with your own thinking visible on top.',
        },
      ],
    },
    {
      label: 'When you finish',
      voice: {
        text: 'My mini-portfolio got me into the Level 5 diploma and a paid internship in the same month.',
        name: 'Harriet',
        campus: 'Online',
        surveyed: 'Graduate NPS survey, 2025',
        consent: true,
      },
      items: [
        {
          can: 'Show a portfolio across design, animation and film',
          means: 'Your strongest pieces, revised on feedback, live online and ready to send to a studio or a diploma.',
        },
        {
          can: 'Take a junior creative role',
          means: '84% of 2025 graduates were in a creative job or further study within six months.',
        },
        {
          can: 'Step up to Level 5 or 6',
          means: 'Direct entry into Yoobee diplomas in animation, film, design or game development.',
        },
      ],
    },
  ],
  entry: {
    minAge: 16,
    backgrounds: ['NCEA Level 2 or above', 'A Level 3 creative or digital certificate', 'Worked in a creative or digital role', 'None of these yet'],
    fallback: {
      label: 'the Creative Media Taster',
      weeks: 2,
      href: '#intakes',
      note: 'Do the free two-hour Taster, then an advisor looks at what you have done so far. Many people without NCEA Level 2 get in on equivalent evidence, and the Taster counts.',
    },
  },
  intakes: [
    {
      date: '2027-02-08',
      label: '8 Feb 2027',
      campuses: [
        { name: 'Online, full-time', left: 22 },
        { name: 'Online, part-time', left: 9 },
      ],
    },
    {
      date: '2027-02-22',
      label: '22 Feb 2027',
      campuses: [
        { name: 'City Road, Auckland', left: 4 },
        { name: 'Bunny Street, Wellington', left: 11 },
        { name: 'Colombo Street, Christchurch', left: 0 },
      ],
    },
    { label: 'Jul 2027', unconfirmed: true },
  ],
  pathways: {
    work: 'Junior designer, animator, video editor or content creator in a studio, agency or in-house team. Most 2025 grads started between $48k and $55k.',
    next: 'Yoobee Level 5 and 6 diplomas in animation, film, design or game development. Direct entry from this certificate.',
    before: 'Not sure yet? Do the free two-hour Taster, then talk to an advisor about entry. No commitment either way.',
  },
  faqs: [
    {
      q: 'How is it free? What is the catch?',
      a: 'February 2027 intakes are fees-free for domestic students, funded by Yoobee. No tuition, no levy, no software fee. If you are not a NZ citizen or resident, or you start later in the year, the standard fee is $4,753 and StudyLink loans cover it.',
    },
    {
      q: 'Can I get help with living costs while I study?',
      a: 'Often, yes. The course itself costs you nothing. Separately, because it is a full-time approved programme, you may be eligible for a Student Allowance from StudyLink, which is not a loan, or a living-costs loan of up to $333 a week if you are not. Either way you can also apply for a one-off $1,000 for course-related costs like a laptop. StudyLink decides what you get based on your circumstances.',
    },
    {
      q: 'What happens to a pre-start course I finish before the course starts?',
      a: 'It is cross-credited. Each one is a module of the certificate, so you skip that module and its assessment when you start. Do all three and you are about a fortnight ahead of your class.',
    },
    {
      q: 'What computer do I need?',
      a: 'A laptop or desktop from the last five years that runs Adobe Creative Cloud, a webcam and decent internet. The $1,000 course-related costs you can apply for through StudyLink is usually spent on exactly this.',
    },
    {
      q: 'Can I work while I study?',
      a: 'Yes. Live classes are 10am and 1pm on weekdays, about 15 hours a week. Most online students keep a part-time job. The 38-week part-time option runs evenings if you need to keep working full-time.',
    },
  ],
  formal: {
    level: 4,
    credits: 60,
    campuses: ['Online', 'City Road (Auckland)', 'Bunny Street (Wellington)', 'Colombo Street (Christchurch)'],
    intakesYear: 2027,
    intakesLabel: 'February (online 8 Feb, campus 22 Feb) and July',
    intl: { minAge: 18, ielts: '5.5 (no band under 5)', href: '/international' },
    links: {
      structure: '#formal',
      fees: '#formal',
      support: '#formal',
      enrol: '#intakes',
      refund: '#formal',
    },
  },
}
